### ISSUE TITLE
Update from 3.2.3 to 3.3.6.20220505

### ISSUE THREAD

**Issue by GutierrezJeremy** [jan-win1993/au-packages#1]
During the installation process from 3.2.3 to 3.3.6.20220505 i detected a few issues : 

1. A window pops up during installation (openvpn-connect) and requires some user interaction, so no silent upgrade is possible at the moment. 
 
2. After the installation,  openvpn needs to be closed and restarted again to work like expected ( otherwise no connection is possible and no file can be added which results in a disconnect).

3. After i tried to downgrade openvpn-connect to the previous version, the shortcut and the .exe files didnt work anymore and needed to be uninstalled, only a fresh installation solved this issue.

**Comment by jan-win1993** [comment]
I could not replicate the first issue on multiple workstations and virtual machines.
The second issue I could kind of replicate.
When you upgrade to a newer version via powershell with admin privileges it seems like it automatically start the client as the admin user and your profile doesn't load if the profile was imported by another user. But if you close it and restart as the other user everything works fine. I couldn't find a option to repress the automatic start of OpenVPN Connect. But a profile could always be imported and a connection was always possible.    
The third issue is due to the msi-installer and unfortunately not fixable as far as I am concerned.
